### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by tf** [lsegal/yard-js#2]
What is the status of this project? I think good options for js inline doc generators are still missing. So building on the popular yard might be a really good idea.

Some issues I see:
- `parsejs` still is not a gem. Is there any known reason?
- There seems to be a good amount of YARD monkey patching going on in the core_ext namespace. How much of a technical debt is that? What are the issues preventing YARD server integration?
- Extending the range of supported class constructs (Backbone, Ember) could really increase this libraries usability. Maybe simply making it more configurable would be enough.

Cheers

**Comment by lsegal** [comment]
@tf oh man, huge apologies for never having seen this! :(

> parsejs still is not a gem. Is there any known reason?

`parsejs` was written by @wycats. It would be up to him to publish it, since I don't want to steal his gem name. If he decides to jump on here and say it's cool to publish I'd be okay with taking his code and pushing it up.

> There seems to be a good amount of YARD monkey patching going on in the core_ext namespace. How much of a technical debt is that? What are the issues preventing YARD server integration?

This is not entirely debt, but it does illustrate portions of the API that are not quite granular enough to support such a significant change in YARD's feature set. YARD was *never* designed as a Doxygen-style language agnostic documentation tool (the "R" stands for Ruby after all), so there are definitely some necessary hacks to make this a JavaScript thing. This project is a hack, to be sure. It was written to solve a specific need.

Now, if people wanted to start using this more generally, we might want to look at improving YARD to support languages more agnostically, but that might be difficult without breaking APIs, and it would probably incur quite a bit of complexity in YARD as well. It's not off the table but it's definitely not a priority for me right now.

> Extending the range of supported class constructs (Backbone, Ember) could really increase this libraries usability. Maybe simply making it more configurable would be enough.

Patches accepted. I'm not a heavy user of these libraries, so I'm not entirely sure what configurability would be needed here. Note that YARD is extensible by design, so you could tack on custom plugins to do the things you need in addition to the yard-js core logic. That might be the right first step.

Again apologies for the super late response!

**Comment by wycats** [comment]
@lsegal I would be happy to publish it. Is there anything special I need to do for compatibility with yardjs?

**Comment by lsegal** [comment]
@wycats I don't think so, right now we're using the master branch of the GitHub repo out of the box.

**Comment by wycats** [comment]
@lsegal done

**Comment by lsegal** [comment]
@wycats :+1: thanks!

**Comment by tf** [comment]
@lsegal no problem, I know how it goes :smiley:

As to the issue itself, back when I first asked, I really couldn't find any good options for JS inline doc frameworks. But with things like [jsdoc3](http://usejsdoc.org/) gaining momentum, I really wonder whether we should invest in a javascript doc tool which is not really native to the js ecosystem.

And while it's really cool of @wycats to jump in so quickly and release parsejs, there are alternatives now like [esprima](https://github.com/jquery/esprima), which might be more focused on keeping up with ES6 features etc.

For larger projects with both a lot of ruby and javascript, I still think there could be value in consistent doc syntax. But coupling to ruby infrastructure also hinders extraction of js-only components from such projects.

Last of all, as you mentioned, there's the risk of blurring YARD's scope. As you put it: "the R stands for Ruby".

So while I still open for discussion, I'm a bit more hesitant than when I originally opened the issue.

**Comment by pedz** [comment]
Hi,
I'm new to yard and asked a newbie question on google groups.
I came to this git repository because my current project also has javascript.  Currently I was using rdoc and jsdoc3 and external links to get from one set of documentation to the other set.
I don't know if Loren wants to divert yard into this area but I see an area that is currently not covered by any of the documentation tools.
Everything is getting more complex.  Even simple CSS code now is built up from layers of code such as SASS.  Javascript code tickles various things such as classes on HTML elements that interacts with the CSS produced by SASS.  And of course, Ruby is driving the whole back end.
All these pieces interact with each other and, to me, it is frustrating that they can not all be documented together.
In his talk at Rubyconf, Loren talked about contracts and that is very key and important.  But there is also a need to teach or train a new person learning a complex code base that is built up from several languages.  Indeed... I can't even remember how all the pieces interact with each other in my own little projects.  I call this "documentation".  But it is not contracts but elaborate explanations of where, why, and how.  The classic examples of this are [TeX: The Program](http://www.amazon.com/Computers-Typesetting-B-TeX-Program/dp/0201134373/ref=sr_1_1?s=books&ie=UTF8&qid=1450242019&sr=1-1&keywords=tex+the+program) and [Metafont: The Program](http://www.amazon.com/Computers-Typesetting-D-Metafont-Program/dp/0201134381/ref=sr_1_1?ie=UTF8&qid=1450242064&sr=8-1&keywords=metafont+the+program)
Given the new whim of separation of responsibilities, the Ruby code is here, the Javascript code is there, and the CSS code is over yonder.  A single, unified, external, document that covers the entire project would be extremely nice to have.
Getting yard-js to be more a part of yard seems like a plausible step.  But, as Tim points out, it is a completely new direction for yard.
What is unfortunate but not surprising is that the various tools like jsdoc3 and yard can not all pump their metadata into a common place and then `pick your tool` interprets that metadata and produces the HTML pages or whatever output the user wants.  That seems to imply that all the documentation tools (yard, rdoc, jsdoc3, doxygen) are not focused on a single task but actually two tasks: 
 1. pull the documentation "stuff" from the original language files
 2. create pretty HTML pages.

I truly hope this isn't taken as criticism of yard or any of the current tools.  I just wanted to express some of the pains that I feel, the needs that I see, and desire that I have.

**Comment by lsegal** [comment]
@pedz part of the point of the yard-js plugin is to show that YARD *can* take data from multiple sources and feed them into a database that can then be post-processed into something else, where "something else" is most commonly (but not always) HTML. In other words, it would be possible to write plugins to process CSS / HTML and dump them into the same yardoc database to generate HTML from if that was a goal. This is already true for JS (with this project).

The bigger problem isn't a technical one, it's an information design problem. It's one thing to dump Ruby classes alongside CSS stylesheets-- it's a completely different thing to actually communicate this information properly to developers. Practically speaking, you have multiple audiences for these two codebases, and similarly you have multiple contexts for looking up this documentation. To that end, you usually end up with completely different templates to the extent that they could just as well have been generated by multiple tools.

At the end of the day, you don't need to use a single documentation tool for all your documentation. In fact, I would argue that no single documentation tool is going to be the best at documenting everything. In this case, `yard-js` solves a specific need that no other doc tool was properly solving and it just so happened to fit into our development pipeline.

**Comment by pedz** [comment]
I need to go play with this tool but I am confused.  In the readme, bottom of the page, "Known Issues" it says "This plugin cannot document Ruby code alongside JavaScript code".  Am I not understanding what that is trying to tell me (or perhaps it is out of date)?  If I have to make two passes, that's fine.  Or if I need to help and modify yard-js, that is fine too.  I learn more by doing so that may be the easiest next step.

**Comment by lsegal** [comment]
@pedz the point about `yard-js` is that it can't load Ruby and JS code in the same process due to certain restrictions about YARD's architecture, but multiple runs can be used on the same yard db to create all the objects. That said, my points from above still exist, and the templates are still designed for "either or"-- there's really no information in the templates that would show which language the class/module/method is from, so if you generated a bunch of Ruby classes in `yard-js` they would render as if they were JS classes. It's possible to make it work for both together, but that's not what was done here (since there was no need to do both).

**Comment by lsegal** [comment]
Closing this stale issue.
