### ISSUE TITLE
yard-js execution error

### ISSUE THREAD

**Issue by KamalPatel365** [lsegal/yard-js#3]
command: **bundle exec yard -m markdown -e lib/yard-js.rb**
-
### _**ERROR**_:
bundler: failed to load command: yard (/home//.gem/ruby/2.3.0/bin/yard)
RuntimeError: can't modify frozen String
/home//workspace/sdk-documentation/yard//src/lib/yard-js/core_ext/yard.rb:9:in` replace' /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/core_ext/yard.rb:9:in <top (required)>'
/home//workspace/sdk-documentation/yard//src/lib/yard-js/plugin.rb:1:in require_relative' /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/plugin.rb:1:in <top (required)>'
lib/yard-js.rb:2:in require_relative' lib/yard-js.rb:2:in <top (required)>'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in load' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in load_script'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:28:in block in common_options' /usr/local/lib/ruby/2.3.0/optparse.rb:1571:in block in parse_in_order'
/usr/local/lib/ruby/2.3.0/optparse.rb:1527:in catch' /usr/local/lib/ruby/2.3.0/optparse.rb:1527:in parse_in_order'
/usr/local/lib/ruby/2.3.0/optparse.rb:1521:in order!' /usr/local/lib/ruby/2.3.0/optparse.rb:1613:in permute!'
/usr/local/lib/ruby/2.3.0/optparse.rb:1635:in parse!' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:56:in parse_options'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:535:in optparse' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardopts_command.rb:42:in parse_arguments'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:292:in parse_arguments' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:248:in run'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:14:in run' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:72:in run'
/home//.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:54:in run' /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/bin/yard:13:in <top (required)>'
/home//.gem/ruby/2.3.0/bin/yard:23:in load' /home/****/.gem/ruby/2.3.0/bin/yard:23:in <top (required)>'

**Comment by trivikr** [comment]
@KamalPatel365 How did you unblock yourself from this error?

**Comment by KamalPatel365** [comment]
Not resolved yet

**Comment by trivikr** [comment]
Findings after consulting with Ruby expert @mullermp
* The replace is being called on frozen string https://github.com/lsegal/yard-js/blob/2dac43322c76a7b5fb5e5b9196ffde9448d4e76f/lib/yard-js/core_ext/yard.rb#L9
* The string `NSEP` is defined in yard https://github.com/lsegal/yard/blob/359006641260eef1fe6d28f5c43c7c98d40f257d/lib/yard/code_objects/base.rb#L34
* And the string is frozen https://github.com/lsegal/yard/blob/359006641260eef1fe6d28f5c43c7c98d40f257d/lib/yard/code_objects/base.rb#L1

Suggestion: Post a PR on yard-js to make it friendly to frozen strings.
If the fix is immediately required, the dependency can be switched to fork.

Commit which enabled support for frozen_string_literals in yard https://github.com/lsegal/yard/pull/1012

**Comment by KamalPatel365** [comment]
Okay sure

**Comment by trivikr** [comment]
Minimal repo for reproducing the issue: https://github.com/trivikr/yard-js-test/tree/frozen-string-error

**Comment by trivikr** [comment]
Fix is posted at https://github.com/lsegal/yard-js/pull/4
